# Generated by Django 4.1.3 on 2022-11-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('exerciseId', models.IntegerField()),
                ('group1', models.DecimalField(decimal_places=2, max_digits=2)),
                ('group2', models.DecimalField(decimal_places=2, max_digits=2)),
                ('group3', models.DecimalField(decimal_places=2, max_digits=2)),
                ('group4', models.DecimalField(decimal_places=2, max_digits=2)),
                ('group5', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
