# Generated by Django 4.1.3 on 2022-11-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e0', models.IntegerField()),
                ('e1', models.IntegerField()),
                ('e2', models.IntegerField()),
                ('e3', models.IntegerField()),
                ('e4', models.IntegerField()),
                ('e5', models.IntegerField()),
                ('e6', models.IntegerField()),
                ('e7', models.IntegerField()),
                ('e8', models.IntegerField()),
                ('e9', models.IntegerField()),
                ('e10', models.IntegerField()),
                ('e11', models.IntegerField()),
                ('e12', models.IntegerField()),
                ('e13', models.IntegerField()),
                ('e14', models.IntegerField()),
                ('e15', models.IntegerField()),
            ],
        ),
    ]
